SDL.remoteControlCapability = 
{
    climateControlCapabilities: [{
        moduleName: 'Climate Control Module',
        currentTemperatureAvailable: true,
        fanSpeedAvailable: true,
        desiredTemperatureAvailable: true,
        acEnableAvailable: true,
        acMaxEnableAvailable: true,
        circulateAirEnableAvailable: true,
        autoModeEnableAvailable: true,
        dualModeEnableAvailable: true,
        defrostZoneAvailable: true,
        defrostZone: ['FRONT', 'REAR', 'ALL', 'NONE'],
        ventilationModeAvailable: true,
        ventilationMode: ['UPPER', 'LOWER', 'BOTH', 'NONE'],
        heatedWindshieldAvailable: true,
        heatedRearWindowAvailable: true,
        heatedSteeringWheelAvailable: true,
        heatedMirrorsAvailable: true
    }],
    radioControlCapabilities: [{
        moduleName: 'Radio Control Module',
        radioEnableAvailable: true,
        radioBandAvailable: true,
        radioFrequencyAvailable: true,
        hdChannelAvailable: true,
        rdsDataAvailable: true,
        availableHDsAvailable: true,
        hdRadioEnableAvailable: true,
        siriusxmRadioAvailable: true,
        stateAvailable: true,
        signalStrengthAvailable: true,
        signalChangeThresholdAvailable: true,
        sisDataAvailable: true
    }],
    hmiSettingsControlCapabilities: {
        moduleName: 'HMISettingsControlCapabilities',
        distanceUnitAvailable: true,
        temperatureUnitAvailable: true,
        displayModeUnitAvailable: true
    },
    lightControlCapabilities: {
        moduleName: 'Light',
        supportedLights: [{
            name: 'FRONT_LEFT_HIGH_BEAM',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_RIGHT_HIGH_BEAM',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_LEFT_LOW_BEAM',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_RIGHT_LOW_BEAM',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_LEFT_PARKING_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_RIGHT_PARKING_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_LEFT_FOG_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_RIGHT_FOG_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_LEFT_DAYTIME_RUNNING_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_RIGHT_DAYTIME_RUNNING_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_LEFT_TURN_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FRONT_RIGHT_TURN_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_LEFT_FOG_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_RIGHT_FOG_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_LEFT_TAIL_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_RIGHT_TAIL_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_LEFT_BREAK_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_RIGHT_BREAK_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_LEFT_TURN_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_RIGHT_TURN_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_REGISTRATION_PLATE_LIGHT',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'HIGH_BEAMS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'LOW_BEAMS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'FOG_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'RUNNING_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'PARKING_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'BRAKE_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'REAR_REVERSING_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'SIDE_MARKER_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'LEFT_TURN_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'RIGHT_TURN_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'HAZARD_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'AMBIENT_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'OVERHEAD_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'READING_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'TRUNK_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'EXTERIOR_FRONT_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'EXTERIOR_REAR_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'EXTERIOR_LEFT_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }, {
            name: 'EXTERIOR_RIGHT_LIGHTS',
            densityAvailable: true,
            sRGBColorSpaceAvailable: true
        }]
    },
    seatControlCapabilities: [{
        moduleName: 'Seat',
        coolingLevelAvailable: true,
        heatingLevelAvailable: true,
        memoryAvailable: true,
        heatingEnabledAvailable: true,
        verticalPositionAvailable: true,
        headSupportVerticalPositionAvailable: true,
        backVerticalPositionAvailable: true,
        massageModeAvailable: true,
        backTiltAngleAvailable: true,
        coolingEnabledAvailable: true,
        horizontalPositionAvailable: true,
        massageCushionFirmnessAvailable: true,
        massageEnabledAvailable: true,
        frontVerticalPositionAvailable: true,
        headSupportHorizontalPositionAvailable: true
    }],
    buttonCapabilities: [{
        name: 'AC_MAX',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'AC',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'RECIRCULATE',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'FAN_UP',
        shortPressAvailable: true,
        longPressAvailable: true,
        upDownAvailable: false
    }, {
        name: 'FAN_DOWN',
        shortPressAvailable: true,
        longPressAvailable: true,
        upDownAvailable: false
    }, {
        name: 'TEMP_UP',
        shortPressAvailable: true,
        longPressAvailable: true,
        upDownAvailable: false
    }, {
        name: 'TEMP_DOWN',
        shortPressAvailable: true,
        longPressAvailable: true,
        upDownAvailable: false
    }, {
        name: 'DEFROST_MAX',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'DEFROST',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'DEFROST_REAR',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'UPPER_VENT',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'LOWER_VENT',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'VOLUME_UP',
        shortPressAvailable: true,
        longPressAvailable: true,
        upDownAvailable: false
    }, {
        name: 'VOLUME_DOWN',
        shortPressAvailable: true,
        longPressAvailable: true,
        upDownAvailable: false
    }, {
        name: 'EJECT',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'SOURCE',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'SHUFFLE',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }, {
        name: 'REPEAT',
        shortPressAvailable: true,
        longPressAvailable: false,
        upDownAvailable: false
    }],
    audioControlCapabilities: [{
        moduleName: 'AudioControlCapabilities',
        sourceAvailable: true,
        volumeAvailable: true,
        equalizerAvailable: true,
        equalizerMaxChannelId: 100
    }]
}
    